# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Marchant Research Profile
email: tom.marchant@christie.nhs.uk
description: > # this means to ignore newlines until "baseurl:"
  Tom Marchant Clinical Scientist at Christie Hospital,
  Manchester, UK. This site is a personal repository for my research publications
  and presentations.
baseurl: "/researchprofile" # the subpath of your site, e.g. /blog
url: "http://temarchant.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  temarchant

# Build settings
markdown: kramdown
